export const SET_USER = "SET_USER";
export const SET_CHATS = "SET_CHATS";
export const SET_MESSAGES = "SET_MESSAGES";
export const SET_TOTAL_MESSAGES_COUNT = "SET_TOTAL_MESSAGES_COUNT";
export const SET_SELECTED_CHAT = "SET_SELECTED_CHAT";
export const SET_IS_SELECTED_CHAT = "SET_IS_SELECTED_CHAT";
//reply
export const ADD_REPLY_MESSAGE = "ADD_REPLY_MESSAGE";
//EDIT
export const ADD_EDITED_MESSAGE = "ADD_EDITED_MESSAGE";
//add reaction onmessage
export const ADD_REACTION_ON_MESSAGE = "ADD_REACTION_ON_MESSAGE";
//remove/unsent/remove all/back action
export const REMOVE_UNSENT_MESSAGE = "REMOVE_UNSENT_MESSAGE";


export const CLEAR_MESSAGES = "CLEAR_MESSAGES";

//update message status
export const UPDATE_MESSAGE_STATUS = "UPDATE_MESSAGE_STATUS";
export const UPDATE_CHAT_STATUS = "UPDATE_CHAT_STATUS";
export const DELETE_CHAT = "DELETE_CHAT";
export const BLOCK_CHAT = "BLOCK_CHAT";
export const LEAVE_CHAT = "LEAVE_CHAT";
export const LEAVE_FROM_GROUP_CHAT="LEAVE_FROM_GROUP_CHAT"
export const UPDATE_LATEST_CHAT_MESSAGE = "UPDATE_LATEST_CHAT_MESSAGE";
export const UPDATE_CHAT_MESSAGE_AFTER_ONLINE_FRIEND = "UPDATE_CHAT_MESSAGE_AFTER_ONLINE_FRIEND";
//SET_GROUP_USERS_ON_FETCHING

export const SET_GROUP_USERS_ON_FETCHING = "SET_GROUP_USERS_ON_FETCHING";
//remove  admin FROM GROUP CHAT
export const REMOVE_ADMIN_FROM_GROUP_CHAT = "REMOVE_ADMIN_FROM_GROUP_CHAT";
export const MAKE_AS_ADMIN_TO_GROUP_CHAT = "MAKE_AS_ADMIN_TO_GROUP_CHAT";
//remove user from group as a  admin
export const REMOVE_USER_FROM_GROUP = "REMOVE_USER_FROM_GROUP"
//UPDATE_GROUP_INFO
export const UPDATE_GROUP_INFO = "UPDATE_GROUP_INFO";
//S
export const SEEN_PUSH_USER_GROUP_MESSAGE = "SEEN_PUSH_USER_GROUP_MESSAGE";
//LEAVE_ONLINE_USER

export const LEAVE_ONLINE_USER="LEAVE_ONLINE_USER"

//UPDATE ONLINE_STATUS
export const UPDATE_ONLINE_STATUS = "UPDATE ONLINE_STATUS"
//call

export const SENT_CALL_INVITATION = "SENT_CALL_INVITATION";
export const RECEIVE_CALL_INVITATION = "RECEIVE_CALL_INVITATION";
export const ACCEPT_CALL = "ACCEPT_CALL";
export const REJECT_CALL = "REJECT_CALL";
export const USER_CALL_ACCEPTED = "USER_CALL_ACCEPTED";
export const USER_CALL_REJECTED = "USER_CALL_REJECTED";

export const CLEAR_CALL = "CLEAR_CALL";
///UPDATE CALL COUNT


export const UPDATE_ON_CALL_COUNT = "UPDATE_ON_CALL_COUNT";