export const SET_USER = "SET_USER";
export const SET_CHATS = "SET_CHATS";
export const SET_MESSAGES = "SET_MESSAGES";
export const SET_TOTAL_MESSAGES_COUNT = "SET_TOTAL_MESSAGES_COUNT";
export const SET_SELECTED_CHAT = "SET_SELECTED_CHAT";

//reply
export const ADD_REPLY_MESSAGE = "ADD_REPLY_MESSAGE";
//EDIT
export const ADD_EDITED_MESSAGE = "ADD_EDITED_MESSAGE";
//add reaction onmessage
export const ADD_REACTION_ON_MESSAGE = "ADD_REACTION_ON_MESSAGE";
//remove/unsent/remove all/back action
export const REMOVE_UNSENT_MESSAGE = "REMOVE_UNSENT_MESSAGE";


export const CLEAR_MESSAGES = "CLEAR_MESSAGES";

//update message status
export const UPDATE_MESSAGE_STATUS = "UPDATE_MESSAGE_STATUS";
export const UPDATE_CHAT_STATUS = "UPDATE_CHAT_STATUS";
export const DELETE_CHAT = "DELETE_CHAT";
export const BLOCK_CHAT = "BLOCK_CHAT";
export const LEAVE_CHAT = "LEAVE_CHAT";
export const LEAVE_FROM_GROUP_CHAT="LEAVE_FROM_GROUP_CHAT"
export const UPDATE_LATEST_CHAT_MESSAGE = "UPDATE_LATEST_CHAT_MESSAGE";
export const UPDATE_CHAT_MESSAGE_AFTER_ONLINE_FRIEND = "UPDATE_CHAT_MESSAGE_AFTER_ONLINE_FRIEND";